### ISSUE TITLE
unable to clone repo

### ISSUE THREAD

**Issue by kibria-miran** [Ahmadrezagh/AdminPanelLaravel9-Persian#2]
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by Ahmadrezagh** [comment]
I think you used ssh link to clone repository,
I suggest you to use HTTPS url to clone repository.
HTTPS : https://github.com/Ahmadrezagh/AdminPanelLaravel9-Persian.git
